import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Clone Trello",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={
                    inter.className +
                    " bg-gradient-to-r from-cyan-500 via-purple-500 to-pink-500"
                }
            >
                {children}
            </body>
        </html>
    );
}
